### ISSUE TITLE
你配置文件里的三码没清

### ISSUE THREAD

**Issue by keoy** [cheney2001/Hackintosh-Gigabyte-B460M-Aorus-Pro-OpenCore#1]
我就提醒下。

**Comment by cheney2001** [comment]
谢谢提醒，我这份的三码是重新生成过后才push的&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cheney2001/Hackintosh-Gigabyte-B460M-Aorus-Pro-OpenCore"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月9日(星期二) 晚上10:17
收件人:&nbsp;"cheney2001/Hackintosh-Gigabyte-B460M-Aorus-Pro-OpenCore"<Hackintosh-Gigabyte-B460M-Aorus-Pro-OpenCore@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[cheney2001/Hackintosh-Gigabyte-B460M-Aorus-Pro-OpenCore] 你配置文件里的三码没清 (#1)





 
我就提醒下。
